### ISSUE TITLE
Cannot add blog entries for registered user

### ISSUE THREAD

**Issue by wcrisafu** [oqtane/oqtane.blogs#4]
I logged as host, created a new page, added the blog. Modified permission for registered users to view/edit. created a blog (as Host), created entry (as host). It worked. 

On a separate browser I logged as user, went to the page with the blog. created a blog (worked!). Added entry (no errors, and there is a line into the log table that blog was added) but I do not see the entry on the page. Check the blog table but I only see the entries as host.

**Comment by sbwalker** [comment]
I can confirm this is an issue and need to be resolved by implementing the entityid pattern for the custom auth policy. Thank you for reporting.

**Comment by sbwalker** [comment]
this has now been resolved in the code
