### ISSUE TITLE
[ENH] - add the ability of viewers to add comments to the blog 

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.blogs#48]

**Comment by sbwalker** [comment]
@vnetonline are you offering to add these enhancements to this open source project?

**Comment by vnetonline** [comment]
Yes I am going to add these enhancements to this report, because I think they are needed, I thought rather then forking and creating my own Blog module why not just add these enhancements to this repo.

**Comment by sbwalker** [comment]
@vnetonline absolutely!

**Comment by sbwalker** [comment]
done in #70
