### ISSUE TITLE
Explain how to use Widgets

### ISSUE THREAD

**Issue by DiegelB** [oqtane/oqtane.blogs#69]
Love the module! Could you shine some light on how to use the widgets? When I create the widget, Latest Blog, I want to add a template to it. When I try and use the LatestBlog.razor template it just prints out that string to the screen. I may be missing something however.

Thanks!

**Comment by sbwalker** [comment]
I think the Widgets should have default templates to use as examples similar to how there are default templates for the Summary and Detail views

**Comment by zyhfish** [comment]
Hi @DiegelB ,
Here is some examples of the widget templates:

**Popular Posts**
```
<div class="popularposts">
    <h3>
        Popular Posts
    </h3>
    <ul>
        <#itemtemplate>
        <li>
            <div>
                [THUMBNAIL]
            </div>
            <div>
                <a href="[URL]">[TITLE]</a><span>[PUBLISHEDON]</span>
            </div>
        </li>
        </#itemtemplate>
    </ul>
    <a class="read-more" href="[BLOGURL]">Read More</a>
</div>
```

**Categories**
```
<div class="categories">
    <h3>
        Categories
    </h3>
    <div>
        <ul>
            <#itemtemplate>
            <li>
                <a href="[URL]">[NAME] ([COUNT]) </a>
            </li>
            </#itemtemplate>
        </ul>
    </div>
</div>
```

**Related Posts**
```
<div class="relatedposts">
    <h4>
        Related Posts
    </h4>
    <ul>
        <#itemtemplate>
        <li>
            <div>
                [THUMBNAIL]
            </div>
            <div>
                <a href="[URL]">[TITLE]</a>
                <div>
                    [SUMMARY]
                </div>
            </div>
        </li>
        </#itemtemplate>
    </ul>
</div>
```

**Archives**
```
<div class="archives">
    <h3>
        Archives
    </h3>
    [ITEMS]
</div>
```

**Latest Blogs**
```
<div class="latestposts">
    <h4>
        Latest Posts
    </h4>
    <ul>
        <#itemtemplate>
        <li>
            <div>
                [THUMBNAIL]
            </div>
            <div>
                <a href="[URL]">[TITLE]</a>
                <div>
                    [SUMMARY]
                </div>
            </div>
        </li>
        </#itemtemplate>
    </ul>
</div>
```

The supported tokens are listed below:
**ID**: the blog id.
**TITLE**: the blog title.
**SLUG**: the blog slug.
**VIEWS**: views of the blog.
**THUMBNAILPATH**: thumbnail path.
**ALTERNATETEXT**: thumbnail's alternate text.
**THUMBNAIL**: the full img tag of thumbnail.
**CATEGORIES**: the blog categories list with ul-li tags.
**TAGS**: the blog tags list with ul-li tags.
**SUMMARY**: the blog summary.
**CONTENT**: the blog content.
**CREATEDBY**: author of the blog.
**CREATEDON**: the blog creation time with short date string format.
**URL**: the blog url.
**PUBLISHEDON**: the blog publish date with "MMMM dd, yyyy" format.
**PUBLISHDAY**: the day of blog publish date with "dd" format.
**PUBLISHMONTH**", the month of blog publish date with "MMMM" format.

**Comment by DiegelB** [comment]
You both are awesome. Thank you!
