### ISSUE TITLE
Error in page Index.razor

### ISSUE THREAD

**Issue by zoltanhalasz** [oqtane/oqtane.blogs#9]
Let me point out a bug in your Blog code, page Index.razor, lines 73-75 in your repo:
blogid should be simply id, otherwise the selected blog post will be wrong
            if (PageState.QueryString.ContainsKey("blogid"))
            {
                _blogs = new List<Blog>();
                _blogs.Add(await BlogService.GetBlogAsync(int.Parse(PageState.QueryString["blogid"]), ModuleState.ModuleId));
            }

**Comment by sbwalker** [comment]
fixed in #11
